name: ui-packers
region: nyc
static_sites:
- name: frontend
  build_command: npm run build
  output_dir: dist
  routes:
  - path: /api
    preserve_path_prefix: false
  - path: /crew-api
    preserve_path_prefix: false
  catchall_document: index.html
