name: voidworks-app
services:
- name: web
  source_dir: /
  github:
    repo: your-repo-name
    branch: main
  run_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
    catchall_document: index.html