import { Job, Invoice } from '../types';

export const generateJobReport = (job: Job): { reportUrl: string; reportGenerated: boolean } => {
  if (job.lifecycleState !== 'completed') {
    throw new Error('Cannot generate report for incomplete job');
  }

  const beforePhotos = job.photos?.filter(p => p.type === 'before') || [];
  const afterPhotos = job.photos?.filter(p => p.type === 'after') || [];
  
  if (beforePhotos.length === 0 || afterPhotos.length === 0) {
    throw new Error('Photos required for report generation');
  }

  const reportUrl = `/reports/${job.id}_${Date.now()}.pdf`;
  
  return {
    reportUrl,
    reportGenerated: true,
  };
};

export const calculateJobCost = (job: Job): number => {
  let baseCost = job.estimatedValue;

  if (job.urgency === 'emergency') {
    baseCost *= 1.5;
  }

  switch (job.slaType) {
    case '24h':
      baseCost *= 1.3;
      break;
    case '48h':
      baseCost *= 1.15;
      break;
    default:
      break;
  }

  const propertyConditionMultiplier = job.serviceType === 'hoarder-clearout' ? 1.4 : 1.0;
  baseCost *= propertyConditionMultiplier;

  return Math.round(baseCost * 100) / 100;
};

export const generateInvoice = (job: Job): Invoice => {
  if (job.lifecycleState !== 'verified') {
    throw new Error('Job must be verified before invoice generation');
  }

  if (!job.reportGenerated) {
    throw new Error('Report must be generated before invoice');
  }

  const amount = calculateJobCost(job);
  const dueDate = new Date();
  dueDate.setDate(dueDate.getDate() + 30);

  const invoice: Invoice = {
    id: `INV-${job.id}-${Date.now()}`,
    jobId: job.id,
    immutableJobReference: job.immutableReferenceId,
    amount,
    lineItems: [],
    status: 'pending',
    dueDate: dueDate.toISOString(),
    pdfUrl: `/invoices/${job.id}_invoice.pdf`,
    contractType: 'one-off',
    generatedAt: new Date().toISOString(),
    autoGenerated: true,
    locked: true,
  };

  return invoice;
};

export const canGenerateReport = (job: Job): boolean => {
  return job.lifecycleState === 'completed' && !job.reportGenerated;
};

export const canGenerateInvoice = (job: Job): boolean => {
  return job.lifecycleState === 'verified' && !!job.reportGenerated && !job.invoiceId;
};
