import { Job, Invoice, InvoiceLineItem } from '../types';

export const calculateBaseJobCost = (job: Job): number => {
  const sizeMultipliers = { S: 1.0, M: 1.3, L: 1.6, XL: 2.0 };
  const multiplier = job.jobSize ? sizeMultipliers[job.jobSize] : 1.0;
  return Math.round(job.estimatedValue * multiplier);
};

export const calculateEmergencyPremium = (job: Job, baseCost: number): number => {
  return job.urgency === 'emergency' ? Math.round(baseCost * 0.5) : 0;
};

export const calculateSLACharge = (job: Job, baseCost: number): number => {
  const slaMultipliers = { '24h': 0.3, '48h': 0.15, 'standard': 0 };
  return Math.round(baseCost * slaMultipliers[job.slaType]);
};

export const calculateRiskSurcharge = (job: Job, baseCost: number): number => {
  if (!job.riskFlags || job.riskFlags.length === 0) return 0;
  
  const riskMultipliers = {
    'biohazard': 0.4,
    'hoarding': 0.3,
    'fire-damage': 0.2,
    'flood-damage': 0.2,
    'structural': 0.25,
    'asbestos': 0.5,
  };

  const totalMultiplier = job.riskFlags.reduce((sum, flag) => {
    return sum + (riskMultipliers[flag] || 0);
  }, 0);

  return Math.round(baseCost * totalMultiplier);
};

export const generateInvoiceLineItems = (job: Job): InvoiceLineItem[] => {
  const baseCost = calculateBaseJobCost(job);
  const emergencyPremium = calculateEmergencyPremium(job, baseCost);
  const slaCharge = calculateSLACharge(job, baseCost);
  const riskSurcharge = calculateRiskSurcharge(job, baseCost);

  const lineItems: InvoiceLineItem[] = [
    {
      id: '1',
      description: `${job.serviceType} - ${job.jobSize || 'Standard'} property`,
      amount: baseCost,
      category: 'base',
    },
  ];

  if (emergencyPremium > 0) {
    lineItems.push({
      id: '2',
      description: 'Emergency response premium',
      amount: emergencyPremium,
      category: 'emergency-premium',
    });
  }

  if (slaCharge > 0) {
    lineItems.push({
      id: '3',
      description: `${job.slaType} SLA commitment`,
      amount: slaCharge,
      category: 'sla-charge',
    });
  }

  if (riskSurcharge > 0) {
    lineItems.push({
      id: '4',
      description: `Risk surcharge (${job.riskFlags?.join(', ')})`,
      amount: riskSurcharge,
      category: 'risk-surcharge',
    });
  }

  return lineItems;
};

export const calculateTotalInvoiceAmount = (lineItems: InvoiceLineItem[]): number => {
  return lineItems.reduce((sum, item) => sum + item.amount, 0);
};

export const generateEnhancedInvoice = (job: Job): Invoice => {
  const lineItems = generateInvoiceLineItems(job);
  const totalAmount = calculateTotalInvoiceAmount(lineItems);
  const dueDate = new Date();
  dueDate.setDate(dueDate.getDate() + 30);

  const invoice: Invoice = {
    id: `INV-${job.id}-${Date.now()}`,
    jobId: job.id,
    immutableJobReference: job.immutableReferenceId,
    amount: totalAmount,
    lineItems,
    status: 'pending',
    dueDate: dueDate.toISOString(),
    pdfUrl: `/invoices/${job.id}_invoice.pdf`,
    contractType: 'one-off',
    generatedAt: new Date().toISOString(),
    autoGenerated: true,
    locked: true,
  };

  return invoice;
};
