import React, { useState, useEffect } from 'react';
import { X, FileText, Download, Check, Sparkles } from 'lucide-react';
import { Job, Invoice, InvoiceLineItem } from '../../types';
import confetti from 'canvas-confetti';

interface InvoiceGenerationModalProps {
  job: Job;
  isOpen: boolean;
  onClose: () => void;
  onComplete: (invoice: Invoice) => void;
}

export const InvoiceGenerationModal: React.FC<InvoiceGenerationModalProps> = ({
  job,
  isOpen,
  onClose,
  onComplete
}) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isGenerated, setIsGenerated] = useState(false);
  const [invoice, setInvoice] = useState<Invoice | null>(null);

  useEffect(() => {
    if (isOpen && !isGenerated) {
      generateInvoice();
    }
  }, [isOpen]);

  const generateInvoice = async () => {
    setIsGenerating(true);
    
    // Simulate invoice generation
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    const lineItems: InvoiceLineItem[] = [
      {
        id: '1',
        description: `${job.serviceType} - ${job.jobSize} property`,
        amount: job.estimatedValue * 0.7,
        category: 'base'
      },
      {
        id: '2',
        description: `${job.slaType} SLA commitment`,
        amount: job.estimatedValue * 0.2,
        category: 'sla-charge'
      }
    ];

    if (job.urgency === 'emergency') {
      lineItems.push({
        id: '3',
        description: 'Emergency response premium',
        amount: job.estimatedValue * 0.1,
        category: 'emergency-premium'
      });
    }

    const newInvoice: Invoice = {
      id: `INV-${Date.now()}`,
      jobId: job.id,
      immutableJobReference: job.immutableReferenceId,
      amount: job.estimatedValue,
      lineItems,
      status: 'pending',
      dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      pdfUrl: `/invoices/INV-${Date.now()}.pdf`,
      paymentMethod: 'stripe',
      contractType: 'one-off',
      generatedAt: new Date().toISOString(),
      autoGenerated: true,
      locked: true
    };

    setInvoice(newInvoice);
    setIsGenerating(false);
    setIsGenerated(true);

    // Trigger confetti
    confetti({
      particleCount: 100,
      spread: 70,
      origin: { y: 0.6 }
    });
  };

  const handleComplete = () => {
    if (invoice) {
      onComplete(invoice);
      onClose();
      setIsGenerated(false);
      setInvoice(null);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg p-6 w-full max-w-2xl">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl font-bold flex items-center">
            <FileText className="mr-2" />
            Invoice Generation
          </h2>
          <button onClick={onClose} className="text-gray-500 hover:text-gray-700">
            <X size={24} />
          </button>
        </div>

        {isGenerating && (
          <div className="text-center py-8">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
            <p className="text-lg">Generating invoice...</p>
            <p className="text-sm text-gray-600">Calculating costs and creating PDF</p>
          </div>
        )}

        {isGenerated && invoice && (
          <div className="space-y-6">
            <div className="bg-green-50 border border-green-200 rounded-lg p-4 flex items-center">
              <Check className="text-green-600 mr-2" size={20} />
              <span className="text-green-800 font-medium">Invoice generated successfully!</span>
            </div>

            <div className="bg-gray-50 p-4 rounded-lg">
              <h3 className="font-semibold mb-3">Invoice Details</h3>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <p><strong>Invoice ID:</strong> {invoice.id}</p>
                  <p><strong>Job Reference:</strong> {invoice.immutableJobReference}</p>
                  <p><strong>Due Date:</strong> {new Date(invoice.dueDate).toLocaleDateString()}</p>
                </div>
                <div>
                  <p><strong>Total Amount:</strong> £{invoice.amount.toLocaleString()}</p>
                  <p><strong>Status:</strong> {invoice.status}</p>
                  <p><strong>Payment Method:</strong> {invoice.paymentMethod}</p>
                </div>
              </div>
            </div>

            <div className="bg-gray-50 p-4 rounded-lg">
              <h3 className="font-semibold mb-3">Line Items</h3>
              <div className="space-y-2">
                {invoice.lineItems.map((item) => (
                  <div key={item.id} className="flex justify-between text-sm">
                    <span>{item.description}</span>
                    <span>£{item.amount.toLocaleString()}</span>
                  </div>
                ))}
                <div className="border-t pt-2 flex justify-between font-semibold">
                  <span>Total</span>
                  <span>£{invoice.amount.toLocaleString()}</span>
                </div>
              </div>
            </div>

            <div className="flex justify-between">
              <button
                className="px-4 py-2 text-blue-600 hover:text-blue-800 flex items-center"
                onClick={() => window.open(invoice.pdfUrl, '_blank')}
              >
                <Download size={16} className="mr-2" />
                Download PDF
              </button>
              
              <button
                onClick={handleComplete}
                className="px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 flex items-center"
              >
                <Sparkles size={16} className="mr-2" />
                Complete Job
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};